language: cpp
env:
  - NODE_VERSION="0.10"
  - NODE_VERSION="0.12"
os:
  - linux
  - osx
matrix:
  fast_finish: true
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
  - source /tmp/.nvm/nvm.sh;
  - nvm install $NODE_VERSION;
  - nvm use --delete-prefix $NODE_VERSION;
install:
  - npm install
  - npm install -g .
  - npm install -g jake
  - npm install -g titanium
  - mkdir ~/.titanium
  - cp ./cli_config.json ~/.titanium/config.json
script:
  - npm test
deploy:
  provider: npm
  email: npmjs@appcelerator.com
  api_key:
    secure: YDvhcMdwm6NX7vAQ7NwqC2m5YakaQhrPios6KfJNbYdd5aAZRyNkmYWRtgZN94zV2v/EmfodqESDdxHi89IoyHcdMX/bf80ECp8gyz/hs5SUeVpCJCeA0YZH5A+b9OabP0daS0iQ5p5/Ns/0ySoU0+J3zsvn5X27rADknsieM5A=
  on:
    tags: true
    repo: appcelerator/alloy
